// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.llh.web.converter;

import com.llh.web.converter.PaisConverter;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PaisConverter_Roo_Configurable {
    
    declare @type: PaisConverter: @Configurable;
    
}
