// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.llh.web.converter;

import com.llh.web.converter.VisitasConverter;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect VisitasConverter_Roo_Configurable {
    
    declare @type: VisitasConverter: @Configurable;
    
}
