// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.llh.domain;

import com.llh.domain.Cliente;
import com.llh.domain.ClienteDataOnDemand;
import com.llh.domain.PaisDataOnDemand;
import com.llh.domain.VisitasDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ClienteDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ClienteDataOnDemand: @Component;
    
    private Random ClienteDataOnDemand.rnd = new SecureRandom();
    
    private List<Cliente> ClienteDataOnDemand.data;
    
    @Autowired
    PaisDataOnDemand ClienteDataOnDemand.paisDataOnDemand;
    
    @Autowired
    VisitasDataOnDemand ClienteDataOnDemand.visitasDataOnDemand;
    
    public Cliente ClienteDataOnDemand.getNewTransientCliente(int index) {
        Cliente obj = new Cliente();
        setApellido(obj, index);
        setFechaNacimineto(obj, index);
        setIdentificacion(obj, index);
        setNombre(obj, index);
        setSegundoApellido(obj, index);
        setSegundoNombre(obj, index);
        setTelefono(obj, index);
        return obj;
    }
    
    public void ClienteDataOnDemand.setApellido(Cliente obj, int index) {
        String apellido = "apellido_" + index;
        obj.setApellido(apellido);
    }
    
    public void ClienteDataOnDemand.setFechaNacimineto(Cliente obj, int index) {
        Date fechaNacimineto = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFechaNacimineto(fechaNacimineto);
    }
    
    public void ClienteDataOnDemand.setIdentificacion(Cliente obj, int index) {
        String identificacion = "identificacion_" + index;
        obj.setIdentificacion(identificacion);
    }
    
    public void ClienteDataOnDemand.setNombre(Cliente obj, int index) {
        String nombre = "nombre_" + index;
        obj.setNombre(nombre);
    }
    
    public void ClienteDataOnDemand.setSegundoApellido(Cliente obj, int index) {
        String segundoApellido = "segundoApellido_" + index;
        obj.setSegundoApellido(segundoApellido);
    }
    
    public void ClienteDataOnDemand.setSegundoNombre(Cliente obj, int index) {
        String segundoNombre = "segundoNombre_" + index;
        obj.setSegundoNombre(segundoNombre);
    }
    
    public void ClienteDataOnDemand.setTelefono(Cliente obj, int index) {
        String telefono = "telefono_" + index;
        obj.setTelefono(telefono);
    }
    
    public Cliente ClienteDataOnDemand.getSpecificCliente(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Cliente obj = data.get(index);
        Long id = obj.getId();
        return Cliente.findCliente(id);
    }
    
    public Cliente ClienteDataOnDemand.getRandomCliente() {
        init();
        Cliente obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Cliente.findCliente(id);
    }
    
    public boolean ClienteDataOnDemand.modifyCliente(Cliente obj) {
        return false;
    }
    
    public void ClienteDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Cliente.findClienteEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Cliente' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Cliente>();
        for (int i = 0; i < 10; i++) {
            Cliente obj = getNewTransientCliente(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
