// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.llh.domain;

import com.llh.domain.PaisIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PaisIntegrationTest_Roo_Configurable {
    
    declare @type: PaisIntegrationTest: @Configurable;
    
}
