// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.llh.domain;

import com.llh.domain.Visitas;
import com.llh.domain.VisitasDataOnDemand;
import com.llh.domain.VisitasIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect VisitasIntegrationTest_Roo_IntegrationTest {
    
    declare @type: VisitasIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: VisitasIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: VisitasIntegrationTest: @Transactional;
    
    @Autowired
    VisitasDataOnDemand VisitasIntegrationTest.dod;
    
    @Test
    public void VisitasIntegrationTest.testCountVisitases() {
        Assert.assertNotNull("Data on demand for 'Visitas' failed to initialize correctly", dod.getRandomVisitas());
        long count = Visitas.countVisitases();
        Assert.assertTrue("Counter for 'Visitas' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void VisitasIntegrationTest.testFindVisitas() {
        Visitas obj = dod.getRandomVisitas();
        Assert.assertNotNull("Data on demand for 'Visitas' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Visitas' failed to provide an identifier", id);
        obj = Visitas.findVisitas(id);
        Assert.assertNotNull("Find method for 'Visitas' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Visitas' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void VisitasIntegrationTest.testFindAllVisitases() {
        Assert.assertNotNull("Data on demand for 'Visitas' failed to initialize correctly", dod.getRandomVisitas());
        long count = Visitas.countVisitases();
        Assert.assertTrue("Too expensive to perform a find all test for 'Visitas', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Visitas> result = Visitas.findAllVisitases();
        Assert.assertNotNull("Find all method for 'Visitas' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Visitas' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void VisitasIntegrationTest.testFindVisitasEntries() {
        Assert.assertNotNull("Data on demand for 'Visitas' failed to initialize correctly", dod.getRandomVisitas());
        long count = Visitas.countVisitases();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Visitas> result = Visitas.findVisitasEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Visitas' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Visitas' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void VisitasIntegrationTest.testFlush() {
        Visitas obj = dod.getRandomVisitas();
        Assert.assertNotNull("Data on demand for 'Visitas' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Visitas' failed to provide an identifier", id);
        obj = Visitas.findVisitas(id);
        Assert.assertNotNull("Find method for 'Visitas' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyVisitas(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Visitas' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VisitasIntegrationTest.testMergeUpdate() {
        Visitas obj = dod.getRandomVisitas();
        Assert.assertNotNull("Data on demand for 'Visitas' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Visitas' failed to provide an identifier", id);
        obj = Visitas.findVisitas(id);
        boolean modified =  dod.modifyVisitas(obj);
        Integer currentVersion = obj.getVersion();
        Visitas merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Visitas' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VisitasIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Visitas' failed to initialize correctly", dod.getRandomVisitas());
        Visitas obj = dod.getNewTransientVisitas(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Visitas' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Visitas' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Visitas' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void VisitasIntegrationTest.testRemove() {
        Visitas obj = dod.getRandomVisitas();
        Assert.assertNotNull("Data on demand for 'Visitas' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Visitas' failed to provide an identifier", id);
        obj = Visitas.findVisitas(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Visitas' with identifier '" + id + "'", Visitas.findVisitas(id));
    }
    
}
