// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.llh.web;

import com.llh.web.ClienteBean;
import java.io.Serializable;

privileged aspect ClienteBean_Roo_Serializable {
    
    declare parents: ClienteBean implements Serializable;
    
    private static final long ClienteBean.serialVersionUID = 1L;
    
}
