// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.llh.web;

import com.llh.web.VisitasBean;
import java.io.Serializable;

privileged aspect VisitasBean_Roo_Serializable {
    
    declare parents: VisitasBean implements Serializable;
    
    private static final long VisitasBean.serialVersionUID = 1L;
    
}
